### ISSUE TITLE
Language for topics

### ISSUE THREAD

**Issue by Arne815** [DataManagementLab/ThesisPortal#189]
By creation of a topics, supervisor can specify the language in which the topic should be written.

- [x] add language checkboxes (de/en) in topic creation form
- [x] add language checkboxes in search
- [x] add language to search results
- [x] add language to topic page

**Comment by netcodedev** [comment]
https://github.com/DataManagementLab/ThesisPortal/commit/7cc379bbaa9301474135d3c44e25370a75e4323f
