### ISSUE TITLE
Build - ReferenceError

### ISSUE THREAD

**Issue by Livvi** [DataManagementLab/ThesisPortal#354]
Hi,
ich wollte den Thesisfinder vorführen und davor nochmal selbst testen, auf der VM läuft er aktuell nicht mehr, npm run build wirft folgenden Fehler. Hast du eine Idee woran das liegt und vllt. einen Tipp wie ich den Fehler beheben kann?
![image](https://github.com/DataManagementLab/ThesisPortal/assets/44965030/7fa294c6-5103-405d-b316-df5e8b7aa70f)

**Comment by netcodedev** [comment]
Hi @Livvi,
Hast du überprüft ob eine Datenbank Instanz auf dem richtigen Port läuft?

**Comment by netcodedev** [comment]
@Livvi Ich habe das soeben auf der VM überprüft und konnte keinen Fehler feststellen. Ich schätze mal es war keine Datenbank instanz gestartet. Ich habe nun die Datenbank und das Projekt gestartet und es ist öffentlich erreichbar
