### ISSUE TITLE
pdf upload button

### ISSUE THREAD

**Issue by Serena290** [DataManagementLab/ThesisPortal#77]
The User wants to be able to upload files (pdf) with further information about a topic, while publishing a new topic. 
There needs to be a button in the inputmask.

- [x] add upload form 
- [x] files should be saved in a separate folder for each topic
- [ ] ~~main directory should be configurable~~

**Comment by Serena290** [comment]
User Story 21

**Comment by netcodedev** [comment]
Main directory cant be configurable for now as it needs to be staticly accessible
